"""empty message

Revision ID: 4d1294b2e7b7
Revises: 613d5feee0f4
Create Date: 2025-03-16 14:59:59.399121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1294b2e7b7'
down_revision: Union[str, None] = '613d5feee0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spicy_bot_history', sa.Column('bot_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spicy_bot_history', 'bot_name')
    # ### end Alembic commands ###
