"""empty message

Revision ID: 729246b92748
Revises: fa9de3e1208e
Create Date: 2025-02-24 15:50:57.959402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729246b92748'
down_revision: Union[str, None] = 'fa9de3e1208e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spicy_users_refresh_tokens', sa.Column('client_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spicy_users_refresh_tokens', 'client_id')
    # ### end Alembic commands ###
