"""empty message

Revision ID: e94b684cfa81
Revises: 4d1294b2e7b7
Create Date: 2025-05-09 01:00:51.927878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94b684cfa81'
down_revision: Union[str, None] = '4d1294b2e7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lang', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lang')
    # ### end Alembic commands ###
